parameters:
  - name: feed
    type: string
    default: MyFeed
  - name: pythonVersion
    type: string
    default: '3.8.10'

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildJob
        pool:
          name: "MyLocalPool"
        steps:
          # Update apt and install pip (and python3-distutils)
          - script: |
              sudo apt-get update
              sudo apt-get install -y python3-pip python3.8-venv
              pip --version
            displayName: 'Install pip with apt'

          - script: |
              python3 -m venv venv
              echo "[global]" > pip.conf
              echo "index-url=https://pkgs.dev.azure.com/exoawktest/5ce4f0b1-c4d9-4069-9782-60242c3d1b35/_packaging/${{ parameters.feed }}/pypi/simple/" >> pip.conf
              # Tell pip to use this configuration
              export PIP_CONFIG_FILE=$(pwd)/pip.conf

          - script: |
              source venv/bin/activate
              pip install poetry
              # Ensure Poetry's bin directory is in the PATH
              export PATH="$HOME/.local/bin:$PATH"
              poetry --version
            displayName: 'Install Poetry with pip'

          - script: echo "##vso[task.prependpath]$HOME/.local/bin"
            displayName: Add poetry to PATH

          - script: |
              source venv/bin/activate
              pip install keyring artifacts-keyring
            displayName: Install artifacts-keyring

          - script: |
              source venv/bin/activate
              poetry config repositories.azure https://pkgs.dev.azure.com/exoawktest/5ce4f0b1-c4d9-4069-9782-60242c3d1b35/_packaging/${{ parameters.feed }}/pypi/simple/
            displayName: 'Configure Poetry Repository'

          # Build the package using Poetry (creates source and wheel distributions)
          - script: |
              source venv/bin/activate
              poetry build
            displayName: 'Build Package'

          # Publish the package to Azure Artifacts using Poetry
          - script: |
              source venv/bin/activate
              poetry publish -r azure -u  $(AZURE_ARTIFACT_USERNAME) -p $(AZURE_ARTIFACT_PASSWORD)
            displayName: 'Publish Package to Azure Artifacts'
            env:
              AZURE_ARTIFACT_USERNAME: $(AZURE_ARTIFACT_USERNAME)
              AZURE_ARTIFACT_PASSWORD: $(AZURE_ARTIFACT_PASSWORD)
