parameters:
  - name: repository
    type: string
    default: https://pkgs.dev.azure.com/exoawktest/5ce4f0b1-c4d9-4069-9782-60242c3d1b35/_packaging/MyFeed/pypi/upload/
  - name: pythonVersion
    type: string
    default: '3.8.10'


stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildJob
        pool:
          name: "MyLocalPool"
        steps:
          # Update apt and install pip (and python3-distutils)
          - script: |
              sudo apt-get update
              sudo apt-get install -y python3-pip python3.8-venv
              pip --version
            displayName: 'Install pip with apt'

          - script: |
              python3 -m venv venv
            displayName: 'Create virtual environment'

          - script: |
              source venv/bin/activate
              pip install poetry keyring artifacts-keyring
            displayName: 'Install Poetry keyring artifacts-keyring with pip'

          - script: |
              source venv/bin/activate
              poetry config repositories.azure ${{ parameters.repository }}
            displayName: 'Configure Poetry Repository'

          # Build the package using Poetry (creates source and wheel distributions)
          - script: |
              source venv/bin/activate
              poetry build
            displayName: 'Build Package'

          # Publish the package to Azure Artifacts using Poetry
          - script: |
              source venv/bin/activate
              poetry publish -r azure -u  $(AZURE_ARTIFACT_USERNAME) -p $(AZURE_ARTIFACT_PASSWORD)
            displayName: 'Publish Package to Azure Artifacts'
            env:
              AZURE_ARTIFACT_USERNAME: $(AZURE_ARTIFACT_USERNAME)
              AZURE_ARTIFACT_PASSWORD: $(AZURE_ARTIFACT_PASSWORD)
