parameters:
  - name: feed
    type: string
    default: MyFeed
  - name: pythonVersion
    type: string
    default: '3.8.10'

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildJob
        pool:
          name: "MyLocalPool"
        steps:
          # Update apt and install pip (and python3-distutils)
          - script: |
              sudo apt-get update
              sudo apt-get install -y python3-pip
              pip3 --version
            displayName: 'Install pip with apt'
            
          - script: |
              pip3 install poetry
              # Ensure Poetry's bin directory is in the PATH
              export PATH="$HOME/.local/bin:$PATH"
              poetry --version
            displayName: 'Install Poetry with pip'

          - script: echo "##vso[task.prependpath]$HOME/.local/bin"
            displayName: Add poetry to PATH

          - script: pip install keyring artifacts-keyring
            displayName: Install artifacts-keyring

          - script: |
              poetry config repositories.azure index-url=https://pkgs.dev.azure.com/exoawktest/5ce4f0b1-c4d9-4069-9782-60242c3d1b35/_packaging/${{ parameters.feed }}/pypi/simple/
              poetry config http-basic.azure $(AZURE_ARTIFACT_USERNAME) $(AZURE_ARTIFACT_PASSWORD)
            displayName: 'Configure Poetry Repository'

          # Build the package using Poetry (creates source and wheel distributions)
          - script: |
              poetry build
            displayName: 'Build Package'

          # Publish the package to Azure Artifacts using Poetry
          - script: |
              poetry publish -r azure -u  $(AZURE_ARTIFACT_USERNAME) -p $(AZURE_ARTIFACT_PASSWORD)
            displayName: 'Publish Package to Azure Artifacts'
            env:
              AZURE_ARTIFACT_USERNAME: $(AZURE_ARTIFACT_USERNAME)
              AZURE_ARTIFACT_PASSWORD: $(AZURE_ARTIFACT_PASSWORD)
