parameters:
  - name: repository
    type: string
    default: https://pkgs.dev.azure.com/exoawktest/5ce4f0b1-c4d9-4069-9782-60242c3d1b35/_packaging/MyFeed/pypi/upload/
  - name: pythonVersion
    type: string
    default: '3.8.10'
  - name: pool
    type: string
    default: MyLocalPool

stages:
  - stage: BuildAndPush
    jobs:
      - job: BuildJob
        pool:
          name: ${{ parameters.pool }}
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ parameters.pythonVersion }}
            displayName: 'Use Python ${{ parameters.pythonVersion }}'

          - script: |
              sudo apt-get update
              sudo apt-get install -y python3-pip python3-venv
              pip --version
            displayName: 'Install pip with apt'

          - script: |
              python -m venv venv
            displayName: 'Create virtual environment'

          - script: |
              source venv/bin/activate
              pip install poetry keyring artifacts-keyring
              poetry --version
            displayName: 'Install Poetry and keyring packages with pip'

          - script: |
              source venv/bin/activate
              poetry config repositories.azure ${{ parameters.repository }}
            displayName: 'Configure Poetry Repository'

          - script: |
              source venv/bin/activate
              poetry build
            displayName: 'Build Package'

          - script: |
              source venv/bin/activate
              poetry publish -r azure -u $(AZURE_ARTIFACT_USERNAME) -p $(AZURE_ARTIFACT_PASSWORD)
            displayName: 'Publish Package to Azure Artifacts'
            env:
              AZURE_ARTIFACT_USERNAME: $(AZURE_ARTIFACT_USERNAME)
              AZURE_ARTIFACT_PASSWORD: $(AZURE_ARTIFACT_PASSWORD)
